#!/usr/bin/env bash

if [ -z $1 ]
then
  echo "Usage: "
  echo ""
  echo "vansi2html filename"
  echo ""
fi

vim $1 -s <(echo -e ":set nu&\n:syntax on\n:TOhtml\n:w! $1.html\n:qa!")
echo "Creating $1.html"
